name: phyloselect
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - iqtree
  - trimal
  - muscle
  - pal2nal
  - fpocket
  - vina
  - openbabel
  - paml
  - biopython
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - requests
  - psutil
  - ete3
  - scipy
  - pip